name: Release

on:
    push:
        tags:
            - '*'

permissions:
    contents: write

jobs:
    release:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v7
              with:
                  fetch-depth: 0

            - name: Build Changelog
              id: github_release
              uses: mikepenz/release-changelog-builder-action@v6
              with:
                  configuration: '.github/changelog_configuration.json'
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

            - name: Create Release
              uses: softprops/action-gh-release@v3
              with:
                  name: Release ${{ github.ref_name }}
                  body: ${{ steps.github_release.outputs.changelog }}
                  draft: false
                  prerelease: false
